apiVersion: release-notes/v2
kind: feature
area: telemetry
issue:
  - https://github.com/khulnasoft/khulnasoft/issues/47835
releaseNotes:
  - |
    **Added** new configuration options to `OpenTelemetryTracingProvider` in `MeshConfig` to allow exporting OpenTelemetry traces via HTTP.
